Kegiatan/urls.py
from django.urls import path

from .views import list_kegiatan,tambah_peserta,tambah_kegiatan

app_name = 'Kegiatan'


urlpatterns = [

    path('', list_kegiatan , name = 'list'),
    path('tambahpeserta', tambah_peserta, name = 'tambahpeserta'),
    path('tambahkegiatan', tambah_kegiatan, name = 'tambahkegiatan'),
]

akordion/urls.py
from django.urls import path
from . import views

app_name = 'akordion'

urlpatterns = [

    path('', views.akordion , name = 'akordion'),

]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [

    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('index2', views.index2, name='index2'),
    path('index4', views.index4, name='index4'),
    path('jadwal', views.jadwal, name='jadwal'),
    path('tambah', views.tambah, name='tambah'),
    path('tambahSubmisi/', views.tambahSubmisi, name='tambahSubmisi'),
    path('updatematkul/<int:pk>/', views.updateMatkul, name='updatematkul'),
    path('deletematkul/<int:pk>/', views.deleteMatkul, name='deletematkul'),
    path('jadwal_detail/<int:pk>/', views.jadwal_detail, name='jadwal_detail'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('kegiatan/',include('Kegiatan.urls',namespace = 'templates')),
    path('akordion/',include('akordion.urls',namespace = 'akordion')),
    path('search/',include('search.urls',namespace = 'search')),
    path('register/', v.register, name='register'),
    path('login/', v.loginPage, name='login'),
    path('logout/', v.logoutUser, name='logout'),
    path('', include("django.contrib.auth.urls")),
    path('register/', include('register.urls', namespace='register')),
]

search/urls.py
from django.urls import path

from .views import fungsi_url,fungsi_data

app_name = 'search'


urlpatterns = [

    path('', fungsi_url , name = 'search'),
    path('data/', fungsi_data),
]

home/models.py
from django.db import models

# Create your models here.
class Jadwal(models.Model):
    nama_matkul = models.CharField(max_length=30)
    nama_dosen = models.CharField(max_length=30)
    sks = models.CharField(max_length=10)
    ruang = models.CharField(max_length=30)
    nama_matkul_panjang = models.CharField(max_length=30,default='')
    jam_kelas = models.CharField(max_length=60,default='')
    

home/forms.py
from django import forms
from .models import Jadwal

class JadwalForm(forms.ModelForm):
	class Meta:
		model = Jadwal
		fields = '__all__'
		

home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Jadwal
from .forms import JadwalForm

# Create your views here.
def index(request):
    context = {"number":1,
                }
    return render(request, 'home/index.html',context)

def index2(request):
    context = {"number":2,
                }
    return render(request, 'home/index2.html',context)

def index4(request):
    context = {"number":3,
                }
    return render(request, 'home/index4.html',context)

def jadwal(request):
    jadwal = Jadwal.objects.all()
    context = {'jadwal':jadwal,
                'number':4}
    return render(request, 'home/jadwal.html', context) 

def jadwal_detail(request, pk):
    jadwal = Jadwal.objects.all().filter(id=pk)
    context = {'jadwal':jadwal,
                'number':4}
    return render(request, 'home/jadwal_detail.html', context) 

def tambah(request):
    context = {'number':4}
    return render(request, 'home/tambah.html', context)

def tambahSubmisi(request):
    form = JadwalForm()
    if (form.is_valid and request.method == 'POST'):
        form = JadwalForm(request.POST)
        form.save()
        return redirect('/jadwal')

    context = {'form':form}
    return render(request, 'home/jadwal.html', context)

def updateMatkul(request, pk):
    matkul = Jadwal.objects.get(id=pk)
    form = JadwalForm(instance=matkul)

    if (form.is_valid and request.method == 'POST'):
        form = JadwalForm(request.POST, instance=matkul)
        form.save()
        return redirect('/jadwal')

    context = {'form':form,'number':4}
    return render(request, 'home/matkul_update.html', context)

def deleteMatkul(request, pk):
    matkul = Jadwal.objects.get(id=pk)
    
    if request.method == "POST":
        matkul.delete()
        return redirect('/jadwal')


    context = {'matkul':matkul,'number':4}
    return render(request, 'home/matkul_delete.html', context)

home/templates/home/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Hello</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|PT+Serif:400,700&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="../../static/home/style2.css">
    <link rel="stylesheet" href="../../static/home/mobile-style.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    {%block meta%} {%endblock meta%}
    
</head>

<body>
    
        
    <div class="container-fluid p-0" >
        <nav class="navbar fixed-bottom navbar-expand-lg navbar-dark bg-primary" >
            
            <a class="navbar-brand" href="{% url 'home:index' %}"> 
              {% if user.is_authenticated %}
              Hello  {{request.user}}
              {% else %}
              {% if number == 1  %} Story3 {% endif %}{% if number == 2  %} Story3 
              {% endif %}{% if number == 3 %} Story1 {% endif %}{% if number == 4 %} Story5 {% endif %}
              {% if number == 5 %} Story6 {% endif %}
              {% if number == 6 %} Story7 {% endif %}
              {% if number == 7 %} Story8 {% endif %}
              {% endif %}
               </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <div class="mr-auto"></div>
              <ul class="navbar-nav">

                  

                <li class="nav-item {% if number == 1 %} active {% endif %}">
                  <a class="nav-link" href="{% url 'home:index' %}">Home </a>
                </li>
                
                <li class="nav-item {% if number == 2 %} active {% endif %}">
                  <a class="nav-link" href="{% url 'home:index2' %}">More About Me</a>
                </li> 
                <li class="nav-item {% if number == 3 %} active {% endif %}">
                    <a class="nav-link" href="{% url 'home:index4' %}">Story 1</a>
                  </li> 
                  <li class="nav-item {% if number == 4 %} active {% endif %}">
                    <a class="nav-link" href="{% url 'home:jadwal' %}">Jadwal</a>
                  </li> 
                  <li class="nav-item {% if number == 5 %} active {% endif %}">
                    <a class="nav-link" href="{% url 'templates:list' %}">Kegiatan</a>
                  </li>
                  <li class="nav-item {% if number == 6 %} active {% endif %}">
                    <a class="nav-link" href="{% url 'akordion:akordion' %}">Akordion</a>
                  </li> 
                  <li class="nav-item {% if number == 7 %} active {% endif %}">
                    <a class="nav-link" href="{% url 'search:search' %}">Search Book</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                  </li> 
                  {% else %}
                  <li class="nav-item {% if number == 8 %} active {% endif %}">
                    <a class="nav-link" href="{% url 'login' %}">Log in</a>
                  </li> 
                  {% endif %}
              </ul>
            </div>
          </nav>
    </div>
    
    
    

    <div class="main-content">
        {% block content %}
        {% endblock %}
    </div>

    
    



    
    

</body>

</html>

home/templates/home/index.html
<!doctype html>
<html lang="en">
  {% extends "home/base.html" %}
  {% load static %}
  {% block content %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style2.css' %}">
    <link rel="stylesheet" href="{% static 'home/mobile-style.css' %}">
    <title>Hello, world!</title>
  </head >
  <body >
    <header id="moree">
        
        <div class="container-fluid p-0 text-left" >
            <div class="col-md-12 p-0" >
              <img src="static/home/mamang.jpg" width="31%" id="mamang" >
              <img src="static/home/bubble.png" width="25%" id ="bubble">
              <img src="static/home/welcome.png" width=25% id="welcome">
              <a href="https://www.instagram.com/zorbax_/" ><img src="static/home/insta.png" alt="" class="icon" id="insta"></a>
              <a href="https://line.me/ti/p/Jajgg2uONy" ><img src="static/home/line.png" alt="" class="icon" id="line"></a>
              <a href="https://steamcommunity.com/id/zorbaxxx/" ><img src="static/home/steam.png" alt="" class="icon" id="steam"></a>
            </div>
        </div>
          
      
      </header>
    <main>
      <section class="section-1">
        <div class = "container text-center">
          <div class="row">
            <div class="col-md-6">
              <div class="profile">
                <img src="static/home/profil.jpg" alt="Profile" id="profil">
              </div>
            </div>

            <div class="col-md-6">
              <div class="panel text-left">
                <h1 class="high text-center">Biodata</h1>
                <p class="pt-3"><table id="tabel1">
                  <tr>
                      <td id="judul">Name</td>
                      <td id="jawab">Rizky Musyaffa Fajari</td>
                  </tr>
                  <tr>
                      <td id="judul">NPM</td>
                      <td id="jawab">1906350755</td>
                  </tr>
                  <tr>
                      <td id="judul">Occupation&nbsp;&nbsp;&nbsp;&nbsp;</td>
                      <td id="jawab">College Student</td>
                  </tr>
                  <tr>
                      <td id="judul">Hobby</td>
                      <td id="jawab">Playing Games, Watch Movie</td>
                  </tr>
                  <tr>
                      <td id="judul">Study at</td>
                      <td id="jawab">University of Indonesia</td>
                  </tr>
                  <tr>
                      <td id="judul">Faculty</td>
                      <td id="jawab">Computer Science</td>
                  </tr>
              </table>
            </p>
              </div>
            </div>


          </div>
        </div>
      
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
  </body>
  {% endblock %}
</html>

home/templates/home/index2.html
<!doctype html>
<html lang="en">
  {% extends 'home/base.html' %}
  {% load static %}
  {% block content %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/style2.css' %}">
    <link rel="stylesheet" href="{% static 'home/mobile-style.css' %}">
    <title>Hello, world!</title>
  </head >
  <body >
    <header id="bgcolor">
        
        <div class="container-fluid text-center" id="more">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4" id="stay" >
                Hello My Name is Rizky Musyaffa Fajari, I was born on February 24th 2001 in Jakarta, I really love playing games
                <a href=#card><img src="static/home/button2.png" id="button1"><img src="static/home/arrow2.png" id="arrow1"></a>
            </div>
            <div class="col-md-4"></div>
        </div> 
        </div>
          
      
    </header>
    <main>
      <section class="section-1">
        <div class = "container text-center" id="card">

            <div class="col-md-12" id="card1">
                <div class="card" style="width: 100%;">
                    <div class="card-body">
                      <h5 class="card-title mb-3">Education</h5>
                      <p class="card-text">SDN 03 KDW Jakarta</br>(2007-2013)</br>SMPN 174 Jakarta</br>(2013-2016)
                                           </br>SMAN 39 Jakarta</br>(2016-2019)</br>Universitas Indonesia</br>(2019-Now)</p>

                    </div>
                  </div>
            </div>

            <div class="col-md-12" id="card2">
                <div class="card" style="width: 100%;">
                    <div class="card-body">
                      <h3 class="card-title mb-3">Skills</h3>
                      <p class="card-text">Word</br>Excel</br>Power Point</p>
                      <h5 class="card-title mb-1">Still Learning on :</h5>
                      <p class="card-text">Java</br>Python</p>
                    </div>
                </div>
                
        </div>
        </div>
        </div>
      
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
  </body>
  {% endblock %}
</html>

home/templates/home/index4.html
<!DOCTYPE html>
<html lang="en">
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">
    <title>Hello</title>
</head>
<body>
    <h1>Welcome Back With Me</h1>
    <img src = "static/home/286405.jpg" alt = "Ganteng" width="400" height="400" style="vertical-align:middle">
    <table>
        <tr>
            <td>Nama</td>
            <td>Rizky Musyaffa Fajari</td>
        </tr>
        <tr>
            <td>NPM</td>
            <td>1906350755</td>
        </tr>
        <tr>
            <td>Angkatan</td>
            <td>2019</td>
        </tr>
        <tr>
            <td>Hobi</td>
            <td>Rebahan</td>
        </tr>
        <tr>
            <td>Deskripsi Saya</td>
            <td>Baik Hati</td>
        </tr>
        <tr>
            <td>Tempat Kuliah</td>
            <td>FASILKOM UI</td>
        </tr>
        
        <tr>
            <td>Riwayat Pendidikan</td>
            <td>SMA</td>
        </tr>
        <tr>
            <td>Media Sosial</td>
            <td>Jieuniee(Steam), coupdegrace24(ID Line)</td>
        </tr>
    </table>
</body>
{% endblock %}
</html>

home/templates/home/jadwal.html
{% extends 'home/base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'home/Story5.css' %}">
    <body>
        <div class="container">
            <h1 class="text-center">
                Daftar Mata Kuliah
            </h1>
            <p>
                
            </p>
        <br>
        {% if user.is_authenticated %}
        <table class="table table-bordered">
          <thead class="thead-dark">
            <tr>
              
              <th scope="col">Matkul</th>
              <th scope="col">Dosen</th>
              <th scope="col">SKS</th>
              <th scope="col">Ruang Kelas</th>
              <th scope="col">Update</th>
              <th scope="col">Delete</th>  
            </tr>
          </thead>
          <tbody>
            {% for matkul in jadwal %}
              <tr>
                <td>
                  <a href="{% url 'home:jadwal_detail' matkul.id %}">{{matkul.nama_matkul}}</a>
                </td>
                <td>
                  {{matkul.nama_dosen}}
                </td>
                <td>
                  {{matkul.sks}}
                </td>
                <td>
                  {{matkul.ruang}}
                </td>
                
                <td class="text-center"><a class="btn btn-sm btn-info" href="{% url 'home:updatematkul' matkul.id %}">Update</a></td>
                <td class="text-center"><a class="btn btn-sm btn-danger" href="{% url 'home:deletematkul' matkul.id %}">Delete</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class="text-center">
          <a class="btn btn-sm btn-info" href='tambah'>TAMBAH</a>
        </div>
        {% else %}
        
          <table class="table table-bordered">
            <thead class="thead-dark">
              <tr>
                
                <th scope="col">Matkul</th>
                <th scope="col">Dosen</th>
                <th scope="col">SKS</th>
                <th scope="col">Ruang Kelas</th>
              </tr>
            </thead>
            <tbody>
              {% for matkul in jadwal %}
                <tr>
                  <td>
                    <a href="{% url 'home:jadwal_detail' matkul.id %}">{{matkul.nama_matkul}}</a>
                  </td>
                  <td>
                    {{matkul.nama_dosen}}
                  </td>
                  <td>
                    {{matkul.sks}}
                  </td>
                  <td>
                    {{matkul.ruang}}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        {% endif %}
        
          
        </div>
        <br><br><br><br><br><br>
        
{% endblock %}

home/templates/home/jadwal_detail.html
{% extends 'home/base.html' %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'home/Story5.css' %}">

<body>
    <div class="container">
        <h1 class="text-center">
             Mata Kuliah Detail
        </h1>
        <p>
        </p>
    <br>
    <div class="row">
        {% if user.is_authenticated %}
    <table class="table table-bordered">
        
        {% for matkul in jadwal %}
            <tr>
                <td id="detail_matkul_keterangan">Nama Singkat Matkul</td>
                <td id="detail_matkul_penjelasan">{{matkul.nama_matkul}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Nama Panjang Matkul</td>
                <td id="detail_matkul_penjelasan">{{matkul.nama_matkul_panjang}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Nama Dosen</td>
                <td id="detail_matkul_penjelasan">{{matkul.nama_dosen}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Waktu Kelas</td>
                <td id="detail_matkul_penjelasan">{{matkul.jam_kelas}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Jumlah SKS</td>
                <td id="detail_matkul_penjelasan">{{matkul.sks}}</td>
            </tr>
            <tr>
                <td id="detail_matkul_keterangan">Ruang Kuliah</td>
                <td id="detail_matkul_penjelasan">{{matkul.ruang}}</td>
            </tr>
        </table>
        </div>      
              <div class="text-center"><a class="btn btn-sm btn-info" href="{% url 'home:updatematkul' matkul.id %}">Update</a></div><br>
              <div class="text-center"><a class="btn btn-sm btn-danger" href="{% url 'home:deletematkul' matkul.id %}">Delete</a></div><br>
            
          {% endfor %}
        
          {% else %}
          <table class="table table-bordered">
        
            {% for matkul in jadwal %}
                <tr>
                    <td id="detail_matkul_keterangan">Nama Singkat Matkul</td>
                    <td id="detail_matkul_penjelasan">{{matkul.nama_matkul}}</td>
                </tr>
                <tr>
                    <td id="detail_matkul_keterangan">Nama Panjang Matkul</td>
                    <td id="detail_matkul_penjelasan">{{matkul.nama_matkul_panjang}}</td>
                </tr>
                <tr>
                    <td id="detail_matkul_keterangan">Nama Dosen</td>
                    <td id="detail_matkul_penjelasan">{{matkul.nama_dosen}}</td>
                </tr>
                <tr>
                    <td id="detail_matkul_keterangan">Waktu Kelas</td>
                    <td id="detail_matkul_penjelasan">{{matkul.jam_kelas}}</td>
                </tr>
                <tr>
                    <td id="detail_matkul_keterangan">Jumlah SKS</td>
                    <td id="detail_matkul_penjelasan">{{matkul.sks}}</td>
                </tr>
                <tr>
                    <td id="detail_matkul_keterangan">Ruang Kuliah</td>
                    <td id="detail_matkul_penjelasan">{{matkul.ruang}}</td>
                </tr>
            </table>
            </div>     
            {% endfor %}
            {% endif %}
      <div class="text-center">
        <a class="btn btn-sm btn-info" href="{% url 'home:jadwal' %}">Kembali</a>
      </div>
    </div>
</body>
{% endblock %}

home/templates/home/matkul_delete.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'home/Story5.css' %}">


<br><br><br><br><br><br>
<body>
<div class="container">
			<p>Apakah anda yakin ingin mata kuliah : {{matkul}}?</p>

			<form  action='' method="post">
				
                {% csrf_token %}
                <div class="text-center">
                    <input class="btn btn-danger" type="submit" name="Hapus">
                    <a class="btn btn-warning" href="/jadwal">Batal</a>
                </div>
				
			</form>	
</div>
{% endblock %}

home/templates/home/matkul_update.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'home/Story5.css' %}">
<br><br>
<body>

<div class="col">
	<form action="" method="post">
        <table class="table">
            {% csrf_token %}
            <thead class="thead-light">
              <tr>
                <th scope="row">Keterangan</th>
                <th scope="row">Data</th>
                
              </tr>
            </thead>
            <tbody>
              <tr>
                {{form}}
              </tr>
              <tr>
            </table>
                <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Update">
                <a class="btn btn-lg btn-block btn-warning" href="/jadwal">Batal</a>
			</form>
        </div>

		
	
</div>


{% endblock content %}

home/templates/home/tambah.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'home/Story5.css' %}">
    <body >
        <div class="container">
            <h1>
                Tambah Data Mata Kuliah
            </h1>
        
        <form action="/tambahSubmisi/" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="exampleFormControlInput1">Nama Mata Kuliah</label>
              <input name="nama_matkul" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nama Singkat Matkul" required>
            </div>
            <div class="form-group">
                <label for="exampleFormControlInput1">Nama Dosen / Pengajar</label>
                <input name="nama_dosen" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nama Panggilan Dosen" required>
              </div>
            <div class="form-group">
              <label for="exampleFormControlSelect1">Jumlah SKS</label>
              <select name="sks" class="form-control" id="exampleFormControlSelect1" required>
                <option>1 SKS</option>
                <option>2 SKS</option>
                <option>3 SKS</option>
                <option>4 SKS</option>
                <option>5 SKS</option>
                <option>6 SKS</option>
              </select>
            </div>
             <label for="exampleFormControlInput1">Ruang Kelas</label>
             <input name="ruang" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Ruang Kelas" required>
             <div class="form-group">
              <label for="exampleFormControlInput1">Nama Mata Kuliah</label>
              <input name="nama_matkul_panjang" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Nama Panjang Matkul" required>
            </div>
            <div class="form-group">
              <label for="exampleFormControlInput1">Waktu Kelas</label>
              <input name="jam_kelas" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Hari Jam" required>
            </div>
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-primary" value="Tambah">
            <a class="btn btn-lg btn-block btn-secondary" href="/jadwal">Batal</a>
            
            
            
            
          </form>
        </div>
        <br><br><br><br>
        </body>
    
{% endblock %}