Kegiatan/urls.py
from django.urls import path

from .views import list_kegiatan,tambah_peserta,tambah_kegiatan

app_name = 'Kegiatan'


urlpatterns = [

    path('', list_kegiatan , name = 'list'),
    path('tambahpeserta', tambah_peserta, name = 'tambahpeserta'),
    path('tambahkegiatan', tambah_kegiatan, name = 'tambahkegiatan'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [

    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('index2', views.index2, name='index2'),
    path('index4', views.index4, name='index4'),
    path('jadwal', views.jadwal, name='jadwal'),
    path('tambah', views.tambah, name='tambah'),
    path('tambahSubmisi/', views.tambahSubmisi, name='tambahSubmisi'),
    path('updatematkul/<int:pk>/', views.updateMatkul, name='updatematkul'),
    path('deletematkul/<int:pk>/', views.deleteMatkul, name='deletematkul'),
    path('jadwal_detail/<int:pk>/', views.jadwal_detail, name='jadwal_detail'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import include, path
from register import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('kegiatan/',include('Kegiatan.urls',namespace = 'templates')),
    path('akordion/',include('akordion.urls',namespace = 'akordion')),
    path('search/',include('search.urls',namespace = 'search')),
    path('register/', v.register, name='register'),
    path('login/', v.loginPage, name='login'),
    path('logout/', v.logoutUser, name='logout'),
    path('', include("django.contrib.auth.urls")),
    path('register/', include('register.urls', namespace='register')),
]

Kegiatan/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan= models.CharField(max_length=30)
    def __str__(self):
        return self.nama_kegiatan

class Peserta(models.Model):
    nama_peserta = models.CharField(max_length=30)
    kegiatan = models.ForeignKey(Kegiatan,null = True, on_delete= models.SET_NULL)

    def __str__(self):
        return self.nama_peserta
    

Kegiatan/forms.py
from django import forms
from .models import Kegiatan, Peserta

class formKegiatan(forms.ModelForm):
    class Meta:
        model = Kegiatan
        fields ="__all__"
    

class formPeserta(forms.ModelForm):
    class Meta:
        model = Peserta
        fields = "__all__"

Kegiatan/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan,Peserta
from .forms import formKegiatan,formPeserta


# Create your views here.
def list_kegiatan(request):
    list_kegiatan = Kegiatan.objects.all()
    data_kegiatan = []
    for kegiatan in list_kegiatan:
        list_peserta = Peserta.objects.filter(kegiatan=kegiatan)
        data_peserta = []
        for peserta in list_peserta:
            data_peserta.append(peserta)
        data_kegiatan.append((kegiatan,data_peserta))
    context = {'data_kegiatan':data_kegiatan,'number':5}
    return render(request,'kegiatan.html',context)



def tambah_peserta(request):
    form = formPeserta()
    if (form.is_valid and request.method == 'POST'):
        form = formPeserta(request.POST)
        form.save()
        return redirect('/kegiatan')
    context = {'form':form,'number':5}
    return render(request,'tambahpeserta.html',context)

def tambah_kegiatan(request):
    form = formKegiatan()
    if (form.is_valid and request.method == 'POST'):
        form = formKegiatan(request.POST)
        form.save()
        return redirect('/kegiatan')

    context = {'form':form,'number':5}
    
    return render(request,'tambahkegiatan.html',context)

Kegiatan/templates/kegiatan.html
<!doctype html>
<html lang="en">
  {% extends "home/base.html" %}
  {% load static %}
  {% block content %}
  
  <main>
    <section class="section-1">
        
      <div class = "container text-center">
        {% if user.is_authenticated %}
        <div class="text-right"><a class="btn btn-sm btn-info" href="tambahkegiatan">Tambah Kegiatan</a></div>
        <h1 class="text-center">
            Daftar Kegiatan
        </h1>
          <div class="row">

            {% for i in data_kegiatan %}
              <div class="card" style="width: 50%;">
                  <div class="card-body">
                    
                    <h5 class="card-title mb-3">{{i.0.nama_kegiatan}}</h5>
                    <p class="card-text">
                        {% for a in i.1 %}
                        <div>{{a.nama_peserta}}</div>
                        {% endfor %}
                        </p>
                        
                        
                </div>
          </div>
          {% endfor %}
          
        </div>
        <br>
        <div class="text-center"><a class="btn btn-sm btn-info" href="{% url 'templates:tambahpeserta' %}">Tambah Peserta</a></div>
      {% else %}
      <h1 class="text-center">
        Daftar Kegiatan
    </h1>
      <div class="row">

        {% for i in data_kegiatan %}
          <div class="card" style="width: 50%;">
              <div class="card-body">
                
                <h5 class="card-title mb-3">{{i.0.nama_kegiatan}}</h5>
                <p class="card-text">
                    {% for a in i.1 %}
                    <div>{{a.nama_peserta}}</div>
                    {% endfor %}
                    </p>
                    
                    
            </div>
      </div>
      {% endfor %}
      
    </div>
    <br>
      {% endif %}
        
        <br><br><br><br><br><br>
    </div>
</div>
    
  </main>
  {% endblock %}

Kegiatan/templates/tambahkegiatan.html
{% extends "home/base.html" %}
  {% load static %}
  {% block content %}
<div class="container">
<form action="" method="post">
    {% csrf_token %}
{{form}}
<input id="submit" type="submit" class="btn btn-lg btn-block btn-info " value="Tambah">
<a class="btn btn-lg btn-block btn-info" href="/kegiatan">Batal</a>
</form>
</div>
{% endblock %}

Kegiatan/templates/tambahpeserta.html
{% extends "home/base.html" %}
  {% load static %}
  {% block content %}
  <div class="container">
<form action="" method="post">
    {% csrf_token %}
{{form}}
<br><br><br><br><br>
<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Tambah">
<a class="btn btn-lg btn-block btn-info" href="/kegiatan">Batal</a>
</form>
</div>
{% endblock %}